from enum import Enum


class PREDICTOR_TYPE(Enum):

    OLS_REGRESSION = 1
    RIDGE_REGRESSION = 2
    LASSO_REGRESSION = 3
    ELASTIC_NET_REGRESSION = 4
    SUPPORT_VECTOR_REGRESSION = 5
    DECISION_TREE_REGERSSIOM = 6
    XGBOOST_REGRESSION = 7
    RANDOM_FOREST_REGRESSION = 8
    LEAST_ANGLE_REGERSSION = 9
    ROBUST_REGRESSION = 10
    LOGISTIC_REGRESSION = 11
    SUPPORT_VECTOR_MACHINES = 12
    K_NEAREST_NEIGHBOUR = 13
    DECISION_TREE_CLASSIFIER = 14
    ARTIFICIAL_NEURAL_NETWORK_CLASSIFIER = 15
    BAGGING_REGRESSOR = 16
    BAGGING_CLASSIFICATION = 17
    XGBOOST_CLASSIFIER = 18
    NAIVE_BAYES_CLASSIFIER = 19
    PY_SYSTEM_TRADE = 20
    EQUAL_WEIGHTED = 21

class REGRESSION_TYPE(Enum):

    OLS = 1
    RIDGE = 2
    LASSO = 3
    ELASTIC_NET = 4
    ROBUST = 5
    BAYESIAN = 6
    SVR = 7
    DECISION_TREE_REGERSSOR = 8
    XGBOOST = 9
    RANDOM_FOREST_REGRESSION = 10
    KERAS_RESNET = 11


class SAMPLING_TYPE(Enum):

    ROLLING = 1
    EXPANDING = 2
    STATIC = 3

class WEIGHTING_SCHEME(Enum):

    EQUAL = 1
    EXPONENTIAL = 2